import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Search, Plus, User2, ArrowLeft, FileText, Printer, Download,
  Pencil, Trash2, Settings2, FilePlus2, Save,
} from "lucide-react";
import { toast } from "sonner";

/* ---------------- helpers ---------------- */

type FieldSchema = { key: string; label: string; type?: "text" | "number" | "textarea" };

function renderTemplate(tpl: string, vars: Record<string, any>) {
  return (tpl || "").replace(/\{\{\s*([a-z_][a-z0-9_]*)\s*\}\}/gi, (_m, k) =>
    vars?.[k] != null && vars[k] !== "" ? String(vars[k]) : `[${k}]`
  );
}

function extractPlaceholders(tpl: string): string[] {
  const set = new Set<string>();
  const re = /\{\{\s*([a-z_][a-z0-9_]*)\s*\}\}/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(tpl || ""))) set.add(m[1]);
  return Array.from(set);
}

function buildDoc(title: string, body: string, customerLine: string) {
  const html = (body || "").replace(/\n/g, "<br/>");
  return `
  <div style="font-family:'SolaimanLipi','Noto Sans Bengali',Arial,sans-serif;max-width:780px;margin:0 auto;color:#0f172a;">
    <div style="text-align:center;border-bottom:3px double #064e3b;padding-bottom:12px;margin-bottom:18px;">
      <div style="font-size:22px;font-weight:800;color:#064e3b;">ইসলামী ব্যাংক বাংলাদেশ পিএলসি</div>
      <div style="font-size:13px;color:#334155;margin-top:2px;">ফকিরবাজার এজেন্ট আউটলেট ১২১/১১, বুড়িচং, কুমিল্লা</div>
      <div style="margin-top:8px;font-size:13px;font-weight:600;">${title}</div>
      <div style="font-size:11px;color:#64748b;">${customerLine}</div>
    </div>
    <div style="font-size:14px;line-height:30px;white-space:pre-wrap;">${html}</div>
    <div style="margin-top:80px;display:flex;justify-content:flex-end;font-size:13px;">
      <div style="text-align:center;">
        <div style="border-top:1px solid #334155;padding-top:4px;min-width:200px;">অনুমোদনকারী</div>
      </div>
    </div>
    <div style="margin-top:24px;text-align:center;font-size:11px;color:#64748b;border-top:1px solid #e2e8f0;padding-top:8px;">
      Generated by: ফকিরবাজার এজেন্ট আউটলেট, ১২১/১১
    </div>
  </div>`;
}

function printDoc(html: string, title = "Document") {
  const w = window.open("", "_blank", "width=900,height=900");
  if (!w) return toast.error("Pop-up blocked");
  w.document.write(`<!doctype html><html><head><title>${title}</title>
    <style>@media print{@page{margin:18mm}} body{margin:0;padding:24px;}</style>
    </head><body>${html}<script>window.onload=()=>{window.print();}</script></body></html>`);
  w.document.close();
}

function downloadDoc(html: string, filename: string) {
  const blob = new Blob([
    `<!doctype html><html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>${filename}</title></head><body>${html}</body></html>`,
  ], { type: "application/msword" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${filename}.doc`;
  a.click();
}

/* ---------------- main ---------------- */

export default function CustomerProfiles() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [manageTypes, setManageTypes] = useState(false);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div>
          <h2 className="text-xl font-bold">গ্রাহক প্রোফাইল ও ফর্ম ম্যানেজমেন্ট</h2>
          <p className="text-xs text-muted-foreground">একাউন্ট নম্বর দিয়ে গ্রাহক খুঁজুন, প্রোফাইল খুলুন, এবং ফর্ম তৈরি/ডাউনলোড করুন</p>
        </div>
        <Button variant="outline" onClick={() => setManageTypes(true)}>
          <Settings2 className="w-4 h-4 mr-1" /> ফর্ম টাইপ ম্যানেজ
        </Button>
      </div>

      {selectedId
        ? <ProfileDetail id={selectedId} onBack={() => setSelectedId(null)} />
        : <ProfileList onOpen={setSelectedId} />}

      <FormTypeManager open={manageTypes} onClose={() => setManageTypes(false)} />
    </div>
  );
}

/* ---------------- list ---------------- */

function ProfileList({ onOpen }: { onOpen: (id: string) => void }) {
  const qc = useQueryClient();
  const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<any>({
    account_number: "", name: "", mobile: "", account_type: "MSA", address: "", notes: "",
  });

  const { data: profiles = [] } = useQuery({
    queryKey: ["customer_profiles"],
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from("customer_profiles").select("*").order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
  });

  const save = useMutation({
    mutationFn: async () => {
      const { error } = await (supabase as any).from("customer_profiles").insert(form);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("প্রোফাইল তৈরি হয়েছে");
      setOpen(false);
      setForm({ account_number: "", name: "", mobile: "", account_type: "MSA", address: "", notes: "" });
      qc.invalidateQueries({ queryKey: ["customer_profiles"] });
    },
    onError: (e: any) => toast.error(e.message),
  });

  const filtered = profiles.filter((p: any) =>
    !search ||
    p.name?.toLowerCase().includes(search.toLowerCase()) ||
    p.account_number?.includes(search) ||
    p.mobile?.includes(search)
  );

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-2 items-center">
        <div className="relative flex-1 min-w-[240px]">
          <Search className="absolute left-2 top-2.5 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="একাউন্ট নং / নাম / মোবাইল"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-8"
          />
        </div>
        <Button onClick={() => setOpen(true)}>
          <Plus className="w-4 h-4 mr-1" /> নতুন গ্রাহক
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {filtered.map((p: any) => (
          <Card
            key={p.id}
            className="p-4 cursor-pointer hover:border-emerald-500 hover:shadow-md transition"
            onClick={() => onOpen(p.id)}
          >
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 text-white flex items-center justify-center text-lg font-bold">
                {p.name?.[0]?.toUpperCase() || <User2 className="w-5 h-5" />}
              </div>
              <div className="min-w-0 flex-1">
                <div className="font-semibold truncate">{p.name}</div>
                <div className="text-[11px] font-mono text-muted-foreground">A/C: {p.account_number}</div>
                {p.mobile && <div className="text-[11px] text-muted-foreground">📱 {p.mobile}</div>}
              </div>
              {p.account_type && <Badge variant="outline">{p.account_type}</Badge>}
            </div>
          </Card>
        ))}
        {filtered.length === 0 && (
          <div className="col-span-full text-center py-10 text-muted-foreground">
            কোনো গ্রাহক প্রোফাইল নেই — উপরে "নতুন গ্রাহক" ক্লিক করুন
          </div>
        )}
      </div>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-xl">
          <DialogHeader><DialogTitle>নতুন গ্রাহক প্রোফাইল</DialogTitle></DialogHeader>
          <div className="grid grid-cols-2 gap-3">
            <div><Label>একাউন্ট নং *</Label><Input value={form.account_number} onChange={(e) => setForm({ ...form, account_number: e.target.value })} /></div>
            <div><Label>নাম *</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div>
            <div><Label>মোবাইল</Label><Input value={form.mobile} onChange={(e) => setForm({ ...form, mobile: e.target.value })} /></div>
            <div><Label>একাউন্ট টাইপ</Label>
              <Select value={form.account_type} onValueChange={(v) => setForm({ ...form, account_type: v })}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {["MSA", "MSSA", "AWCA", "MTDR", "SNDP", "RD", "Others"].map((t) =>
                    <SelectItem key={t} value={t}>{t}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="col-span-2"><Label>ঠিকানা</Label><Input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></div>
            <div className="col-span-2"><Label>নোট</Label><Textarea rows={2} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>বাতিল</Button>
            <Button onClick={() => save.mutate()} disabled={!form.account_number || !form.name || save.isPending}>
              সংরক্ষণ
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ---------------- detail ---------------- */

function ProfileDetail({ id, onBack }: { id: string; onBack: () => void }) {
  const qc = useQueryClient();
  const [editProfile, setEditProfile] = useState(false);
  const [newDocOpen, setNewDocOpen] = useState(false);
  const [editingDoc, setEditingDoc] = useState<any | null>(null);

  const { data: profile } = useQuery({
    queryKey: ["customer_profile", id],
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from("customer_profiles").select("*").eq("id", id).maybeSingle();
      if (error) throw error;
      return data;
    },
  });

  const { data: forms = [] } = useQuery({
    queryKey: ["customer_form_documents", id],
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from("customer_form_documents").select("*, customer_form_types(name, code)")
        .eq("customer_profile_id", id)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
  });

  const del = useMutation({
    mutationFn: async (docId: string) => {
      const { error } = await (supabase as any).from("customer_form_documents").delete().eq("id", docId);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("ডিলিট হয়েছে");
      qc.invalidateQueries({ queryKey: ["customer_form_documents", id] });
    },
  });

  if (!profile) return <div className="text-muted-foreground">লোড হচ্ছে...</div>;

  const grouped = forms.reduce((acc: Record<string, any[]>, f: any) => {
    const key = f.customer_form_types?.name || f.form_type_code || "অন্যান্য";
    (acc[key] ||= []).push(f);
    return acc;
  }, {});

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 flex-wrap">
        <Button variant="ghost" size="sm" onClick={onBack}><ArrowLeft className="w-4 h-4 mr-1" /> ফেরত</Button>
        <Button size="sm" variant="outline" onClick={() => setEditProfile(true)}>
          <Pencil className="w-3.5 h-3.5 mr-1" /> এডিট প্রোফাইল
        </Button>
        <div className="ml-auto">
          <Button size="sm" onClick={() => setNewDocOpen(true)} className="bg-emerald-700 hover:bg-emerald-800">
            <FilePlus2 className="w-4 h-4 mr-1" /> নতুন ফর্ম/আবেদন
          </Button>
        </div>
      </div>

      <Card className="p-5 bg-gradient-to-br from-emerald-50 to-teal-50 border-emerald-200">
        <div className="flex items-center gap-4">
          <div className="w-16 h-16 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 text-white flex items-center justify-center text-2xl font-bold">
            {profile.name?.[0]?.toUpperCase()}
          </div>
          <div className="flex-1">
            <div className="text-lg font-bold">{profile.name}</div>
            <div className="text-sm font-mono">A/C: {profile.account_number}</div>
            <div className="text-xs text-muted-foreground space-x-2">
              {profile.mobile && <span>📱 {profile.mobile}</span>}
              {profile.account_type && <Badge variant="outline">{profile.account_type}</Badge>}
            </div>
            {profile.address && <div className="text-xs text-muted-foreground mt-1">📍 {profile.address}</div>}
          </div>
          <div className="text-right">
            <div className="text-2xl font-bold text-emerald-700">{forms.length}</div>
            <div className="text-[11px] text-muted-foreground">মোট ফর্ম</div>
          </div>
        </div>
        {profile.notes && <div className="text-xs mt-3 p-2 bg-white/60 rounded border">📝 {profile.notes}</div>}
      </Card>

      <div className="space-y-3">
        {Object.keys(grouped).length === 0 && (
          <div className="text-center py-10 text-muted-foreground border rounded-lg border-dashed">
            এই গ্রাহকের কোনো ফর্ম নেই — উপরে "নতুন ফর্ম/আবেদন" ক্লিক করুন
          </div>
        )}
        {(Object.entries(grouped) as [string, any[]][]).map(([typeName, list]) => (
          <Card key={typeName} className="p-3">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-4 h-4 text-emerald-700" />
              <div className="font-semibold">{typeName}</div>
              <Badge variant="secondary">{list.length}</Badge>
            </div>
            <div className="space-y-1.5">
              {list.map((d: any) => (
                <div key={d.id} className="flex items-center gap-2 text-sm border rounded px-2 py-1.5 hover:bg-muted/40">
                  <Badge variant="outline" className="text-[10px]">{d.document_date}</Badge>
                  <span className="flex-1 truncate">{d.title}</span>
                  <Button size="sm" variant="ghost" onClick={() => setEditingDoc(d)}>
                    <Pencil className="w-3.5 h-3.5" />
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => {
                    const html = buildDoc(d.title, d.body, `${profile.name} • A/C ${profile.account_number}`);
                    printDoc(html, d.title);
                  }}>
                    <Printer className="w-3.5 h-3.5" />
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => {
                    const html = buildDoc(d.title, d.body, `${profile.name} • A/C ${profile.account_number}`);
                    downloadDoc(html, d.title);
                  }}>
                    <Download className="w-3.5 h-3.5" />
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => { if (confirm("ডিলিট?")) del.mutate(d.id); }}>
                    <Trash2 className="w-3.5 h-3.5 text-destructive" />
                  </Button>
                </div>
              ))}
            </div>
          </Card>
        ))}
      </div>

      <EditProfileDialog open={editProfile} onClose={() => setEditProfile(false)} profile={profile} />
      {(newDocOpen || editingDoc) && (
        <FormDocumentDialog
          open={true}
          onClose={() => { setNewDocOpen(false); setEditingDoc(null); }}
          profile={profile}
          existing={editingDoc}
        />
      )}
    </div>
  );
}

/* ---------------- edit profile ---------------- */

function EditProfileDialog({ open, onClose, profile }: { open: boolean; onClose: () => void; profile: any }) {
  const qc = useQueryClient();
  const [form, setForm] = useState<any>(profile);
  const save = useMutation({
    mutationFn: async () => {
      const { id, created_at, updated_at, created_by, ...patch } = form;
      const { error } = await (supabase as any).from("customer_profiles").update(patch).eq("id", profile.id);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("আপডেট হয়েছে");
      qc.invalidateQueries({ queryKey: ["customer_profile", profile.id] });
      qc.invalidateQueries({ queryKey: ["customer_profiles"] });
      onClose();
    },
    onError: (e: any) => toast.error(e.message),
  });
  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-xl">
        <DialogHeader><DialogTitle>প্রোফাইল এডিট</DialogTitle></DialogHeader>
        <div className="grid grid-cols-2 gap-3">
          <div><Label>একাউন্ট নং</Label><Input value={form.account_number || ""} onChange={(e) => setForm({ ...form, account_number: e.target.value })} /></div>
          <div><Label>নাম</Label><Input value={form.name || ""} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div>
          <div><Label>মোবাইল</Label><Input value={form.mobile || ""} onChange={(e) => setForm({ ...form, mobile: e.target.value })} /></div>
          <div><Label>একাউন্ট টাইপ</Label><Input value={form.account_type || ""} onChange={(e) => setForm({ ...form, account_type: e.target.value })} /></div>
          <div className="col-span-2"><Label>ঠিকানা</Label><Input value={form.address || ""} onChange={(e) => setForm({ ...form, address: e.target.value })} /></div>
          <div className="col-span-2"><Label>নোট</Label><Textarea rows={2} value={form.notes || ""} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>বাতিল</Button>
          <Button onClick={() => save.mutate()}><Save className="w-4 h-4 mr-1" /> সংরক্ষণ</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

/* ---------------- form document dialog ---------------- */

function FormDocumentDialog({
  open, onClose, profile, existing,
}: { open: boolean; onClose: () => void; profile: any; existing?: any }) {
  const qc = useQueryClient();
  const [typeId, setTypeId] = useState<string>(existing?.form_type_id || "");
  const [title, setTitle] = useState(existing?.title || "");
  const [body, setBody] = useState(existing?.body || "");
  const [values, setValues] = useState<Record<string, any>>(existing?.field_values || {});
  const [docDate, setDocDate] = useState<string>(existing?.document_date || new Date().toISOString().slice(0, 10));

  const { data: types = [] } = useQuery({
    queryKey: ["customer_form_types"],
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("customer_form_types").select("*").order("sort_order");
      if (error) throw error;
      return data || [];
    },
  });

  const selectedType = types.find((t: any) => t.id === typeId);
  const schema: FieldSchema[] = selectedType?.fields_schema || [];

  // Initialize body from template when selecting type (only if not editing)
  function pickType(tid: string) {
    setTypeId(tid);
    const t = types.find((x: any) => x.id === tid);
    if (t) {
      if (!existing) {
        setTitle(t.name);
        setBody(t.body_template || "");
      }
    }
  }

  const mergedVars = useMemo(() => ({
    name: profile.name,
    account_number: profile.account_number,
    mobile: profile.mobile,
    account_type: profile.account_type,
    address: profile.address,
    document_date: docDate,
    ...values,
  }), [profile, docDate, values]);

  // Auto-detect placeholders from body (in case user customized)
  const detectedKeys = useMemo(() => extractPlaceholders(body), [body]);
  const customKeys = detectedKeys.filter((k) =>
    !["name", "account_number", "mobile", "account_type", "address", "document_date"].includes(k) &&
    !schema.some((s) => s.key === k)
  );

  const previewHtml = useMemo(() => {
    const rendered = renderTemplate(body, mergedVars);
    return buildDoc(title || "Document", rendered, `${profile.name} • A/C ${profile.account_number}`);
  }, [body, mergedVars, title, profile]);

  const save = useMutation({
    mutationFn: async () => {
      const payload: any = {
        customer_profile_id: profile.id,
        form_type_id: typeId || null,
        form_type_code: selectedType?.code || null,
        title,
        body,
        field_values: values,
        document_date: docDate,
      };
      if (existing) {
        const { error } = await (supabase as any).from("customer_form_documents").update(payload).eq("id", existing.id);
        if (error) throw error;
      } else {
        const { error } = await (supabase as any).from("customer_form_documents").insert(payload);
        if (error) throw error;
      }
    },
    onSuccess: () => {
      toast.success("সংরক্ষণ সফল");
      qc.invalidateQueries({ queryKey: ["customer_form_documents", profile.id] });
      onClose();
    },
    onError: (e: any) => toast.error(e.message),
  });

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-6xl max-h-[92vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle>{existing ? "ফর্ম এডিট" : "নতুন ফর্ম"} — {profile.name}</DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="fields" className="flex-1 overflow-hidden flex flex-col">
          <TabsList>
            <TabsTrigger value="fields">তথ্য পূরণ</TabsTrigger>
            <TabsTrigger value="body">আবেদন বডি</TabsTrigger>
            <TabsTrigger value="preview">প্রিভিউ</TabsTrigger>
          </TabsList>

          <TabsContent value="fields" className="flex-1 overflow-y-auto">
            <div className="grid md:grid-cols-2 gap-3 p-1">
              <div className="md:col-span-2">
                <Label>ফর্ম টাইপ</Label>
                <Select value={typeId} onValueChange={pickType}>
                  <SelectTrigger><SelectValue placeholder="টাইপ বাছাই করুন" /></SelectTrigger>
                  <SelectContent>
                    {types.map((t: any) => <SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div><Label>শিরোনাম</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} /></div>
              <div><Label>তারিখ</Label><Input type="date" value={docDate} onChange={(e) => setDocDate(e.target.value)} /></div>
              <div className="md:col-span-2 text-xs text-muted-foreground p-2 bg-muted/40 rounded">
                গ্রাহকের নাম, একাউন্ট নং, মোবাইল — অটো ফিল হবে। নিচে শুধু অতিরিক্ত ফিল্ড পূরণ করুন।
              </div>
              {[...schema, ...customKeys.map((k) => ({ key: k, label: k, type: "text" as const }))].map((f) => (
                <div key={f.key} className={f.type === "textarea" ? "md:col-span-2" : ""}>
                  <Label>{f.label}</Label>
                  {f.type === "textarea"
                    ? <Textarea rows={3} value={values[f.key] || ""} onChange={(e) => setValues({ ...values, [f.key]: e.target.value })} />
                    : <Input type={f.type === "number" ? "number" : "text"} value={values[f.key] || ""} onChange={(e) => setValues({ ...values, [f.key]: e.target.value })} />}
                </div>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="body" className="flex-1 overflow-y-auto">
            <div className="text-xs text-muted-foreground p-2 bg-amber-50 border border-amber-200 rounded mb-2">
              ভ্যারিয়েবল ব্যবহার: <code>{"{{name}}, {{account_number}}, {{mobile}}, {{document_date}}"}</code> বা আপনার যেকোনো নতুন কী।
            </div>
            <Textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="font-mono text-sm min-h-[55vh]"
              placeholder="আবেদনের বডি লিখুন বা পেস্ট করুন"
            />
          </TabsContent>

          <TabsContent value="preview" className="flex-1 overflow-y-auto">
            <div className="border rounded bg-white p-4" dangerouslySetInnerHTML={{ __html: previewHtml }} />
          </TabsContent>
        </Tabs>

        <DialogFooter className="border-t pt-3">
          <Button variant="outline" onClick={() => downloadDoc(previewHtml, title || "Document")}>
            <Download className="w-4 h-4 mr-1" /> Word
          </Button>
          <Button variant="outline" onClick={() => printDoc(previewHtml, title || "Document")}>
            <Printer className="w-4 h-4 mr-1" /> Print/PDF
          </Button>
          <Button onClick={() => save.mutate()} disabled={!title || save.isPending}>
            <Save className="w-4 h-4 mr-1" /> সংরক্ষণ
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

/* ---------------- form type manager ---------------- */

function FormTypeManager({ open, onClose }: { open: boolean; onClose: () => void }) {
  const qc = useQueryClient();
  const [editing, setEditing] = useState<any | null>(null);

  const { data: types = [] } = useQuery({
    queryKey: ["customer_form_types"],
    queryFn: async () => {
      const { data, error } = await (supabase as any).from("customer_form_types").select("*").order("sort_order");
      if (error) throw error;
      return data || [];
    },
  });

  const del = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await (supabase as any).from("customer_form_types").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => { toast.success("ডিলিট"); qc.invalidateQueries({ queryKey: ["customer_form_types"] }); },
    onError: (e: any) => toast.error(e.message),
  });

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-4xl">
        <DialogHeader><DialogTitle>ফর্ম টাইপ ম্যানেজ করুন</DialogTitle></DialogHeader>
        {editing ? (
          <FormTypeEditor type={editing} onDone={() => setEditing(null)} />
        ) : (
          <div className="space-y-2">
            <div className="flex justify-end">
              <Button size="sm" onClick={() => setEditing({
                code: "", name: "", description: "", body_template: "", fields_schema: [], sort_order: (types.length + 1) * 10,
              })}>
                <Plus className="w-4 h-4 mr-1" /> নতুন টাইপ
              </Button>
            </div>
            <div className="space-y-1.5 max-h-[60vh] overflow-y-auto">
              {types.map((t: any) => (
                <div key={t.id} className="flex items-center gap-2 border rounded p-2 hover:bg-muted/40">
                  <FileText className="w-4 h-4 text-emerald-700" />
                  <div className="flex-1">
                    <div className="font-medium text-sm">{t.name}</div>
                    <div className="text-[11px] text-muted-foreground">{t.code} • {(t.fields_schema || []).length} ফিল্ড</div>
                  </div>
                  {t.is_system && <Badge variant="secondary" className="text-[10px]">সিস্টেম</Badge>}
                  <Button size="sm" variant="ghost" onClick={() => setEditing(t)}><Pencil className="w-3.5 h-3.5" /></Button>
                  <Button size="sm" variant="ghost" onClick={() => { if (confirm("ডিলিট?")) del.mutate(t.id); }}>
                    <Trash2 className="w-3.5 h-3.5 text-destructive" />
                  </Button>
                </div>
              ))}
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

function FormTypeEditor({ type, onDone }: { type: any; onDone: () => void }) {
  const qc = useQueryClient();
  const [form, setForm] = useState<any>({
    code: type.code || "",
    name: type.name || "",
    description: type.description || "",
    body_template: type.body_template || "",
    fields_schema: type.fields_schema || [],
    sort_order: type.sort_order ?? 100,
  });

  const save = useMutation({
    mutationFn: async () => {
      if (type.id) {
        const { error } = await (supabase as any).from("customer_form_types").update(form).eq("id", type.id);
        if (error) throw error;
      } else {
        const { error } = await (supabase as any).from("customer_form_types").insert(form);
        if (error) throw error;
      }
    },
    onSuccess: () => { toast.success("সংরক্ষিত"); qc.invalidateQueries({ queryKey: ["customer_form_types"] }); onDone(); },
    onError: (e: any) => toast.error(e.message),
  });

  function updField(i: number, patch: any) {
    const a = [...form.fields_schema];
    a[i] = { ...a[i], ...patch };
    setForm({ ...form, fields_schema: a });
  }
  function addField() {
    setForm({ ...form, fields_schema: [...form.fields_schema, { key: "new_field", label: "নতুন ফিল্ড", type: "text" }] });
  }
  function delField(i: number) {
    const a = [...form.fields_schema]; a.splice(i, 1); setForm({ ...form, fields_schema: a });
  }

  return (
    <div className="space-y-3 max-h-[70vh] overflow-y-auto">
      <div className="grid grid-cols-2 gap-3">
        <div><Label>কোড *</Label><Input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="e.g. account_close" /></div>
        <div><Label>নাম *</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div>
        <div className="col-span-2"><Label>বিবরণ</Label><Input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div>
      </div>

      <div>
        <div className="flex justify-between items-center">
          <Label>অতিরিক্ত ফিল্ড (ভ্যারিয়েবল)</Label>
          <Button size="sm" variant="outline" onClick={addField}><Plus className="w-3 h-3 mr-1" /> যোগ</Button>
        </div>
        <div className="space-y-1.5 mt-2">
          {form.fields_schema.map((f: any, i: number) => (
            <div key={i} className="grid grid-cols-12 gap-1">
              <Input className="col-span-4" placeholder="key" value={f.key} onChange={(e) => updField(i, { key: e.target.value })} />
              <Input className="col-span-5" placeholder="লেবেল" value={f.label} onChange={(e) => updField(i, { label: e.target.value })} />
              <Select value={f.type || "text"} onValueChange={(v) => updField(i, { type: v })}>
                <SelectTrigger className="col-span-2"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="text">Text</SelectItem>
                  <SelectItem value="number">Number</SelectItem>
                  <SelectItem value="textarea">Textarea</SelectItem>
                </SelectContent>
              </Select>
              <Button size="sm" variant="ghost" className="col-span-1" onClick={() => delField(i)}>
                <Trash2 className="w-3.5 h-3.5 text-destructive" />
              </Button>
            </div>
          ))}
        </div>
      </div>

      <div>
        <Label>বডি টেমপ্লেট</Label>
        <div className="text-[11px] text-muted-foreground mb-1">
          ব্যবহার করুন: <code>{"{{name}} {{account_number}} {{mobile}} {{document_date}}"}</code> এবং আপনার নিজের ফিল্ড কী।
        </div>
        <Textarea
          rows={14}
          value={form.body_template}
          onChange={(e) => setForm({ ...form, body_template: e.target.value })}
          className="font-mono text-sm"
        />
      </div>

      <DialogFooter>
        <Button variant="outline" onClick={onDone}>বাতিল</Button>
        <Button onClick={() => save.mutate()} disabled={!form.code || !form.name || save.isPending}>সংরক্ষণ</Button>
      </DialogFooter>
    </div>
  );
}
