/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUpcomingPaymentsRouteImport } from './routes/_app/upcoming-payments'
import { Route as AppTargetsRouteImport } from './routes/_app/targets'
import { Route as AppSystemMonitorRouteImport } from './routes/_app/system-monitor'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSmsSendingRouteImport } from './routes/_app/sms-sending'
import { Route as AppSignatureCardsRouteImport } from './routes/_app/signature-cards'
import { Route as AppSalarySheetRouteImport } from './routes/_app/salary-sheet'
import { Route as AppSalaryRouteImport } from './routes/_app/salary'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPendingWorksRouteImport } from './routes/_app/pending-works'
import { Route as AppPartnersRouteImport } from './routes/_app/partners'
import { Route as AppMonthlyReportRouteImport } from './routes/_app/monthly-report'
import { Route as AppLoanLedgerRouteImport } from './routes/_app/loan-ledger'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppExpenseRouteImport } from './routes/_app/expense'
import { Route as AppEmployeeAttendanceRouteImport } from './routes/_app/employee-attendance'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDailyDepositRouteImport } from './routes/_app/daily-deposit'
import { Route as AppCashBookRouteImport } from './routes/_app/cash-book'
import { Route as AppAuditReportRouteImport } from './routes/_app/audit-report'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAgentBankInvestmentRouteImport } from './routes/_app/agent-bank-investment'
import { Route as AppStaffIdRouteImport } from './routes/_app/staff.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpcomingPaymentsRoute = AppUpcomingPaymentsRouteImport.update({
  id: '/upcoming-payments',
  path: '/upcoming-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppTargetsRoute = AppTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemMonitorRoute = AppSystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSmsSendingRoute = AppSmsSendingRouteImport.update({
  id: '/sms-sending',
  path: '/sms-sending',
  getParentRoute: () => AppRoute,
} as any)
const AppSignatureCardsRoute = AppSignatureCardsRouteImport.update({
  id: '/signature-cards',
  path: '/signature-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppSalarySheetRoute = AppSalarySheetRouteImport.update({
  id: '/salary-sheet',
  path: '/salary-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingWorksRoute = AppPendingWorksRouteImport.update({
  id: '/pending-works',
  path: '/pending-works',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlyReportRoute = AppMonthlyReportRouteImport.update({
  id: '/monthly-report',
  path: '/monthly-report',
  getParentRoute: () => AppRoute,
} as any)
const AppLoanLedgerRoute = AppLoanLedgerRouteImport.update({
  id: '/loan-ledger',
  path: '/loan-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseRoute = AppExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeAttendanceRoute = AppEmployeeAttendanceRouteImport.update({
  id: '/employee-attendance',
  path: '/employee-attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyDepositRoute = AppDailyDepositRouteImport.update({
  id: '/daily-deposit',
  path: '/daily-deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppCashBookRoute = AppCashBookRouteImport.update({
  id: '/cash-book',
  path: '/cash-book',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditReportRoute = AppAuditReportRouteImport.update({
  id: '/audit-report',
  path: '/audit-report',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentBankInvestmentRoute = AppAgentBankInvestmentRouteImport.update({
  id: '/agent-bank-investment',
  path: '/agent-bank-investment',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIdRoute = AppStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-bank-investment': typeof AppAgentBankInvestmentRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-report': typeof AppAuditReportRoute
  '/cash-book': typeof AppCashBookRoute
  '/daily-deposit': typeof AppDailyDepositRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/employee-attendance': typeof AppEmployeeAttendanceRoute
  '/expense': typeof AppExpenseRoute
  '/inventory': typeof AppInventoryRoute
  '/loan-ledger': typeof AppLoanLedgerRoute
  '/monthly-report': typeof AppMonthlyReportRoute
  '/partners': typeof AppPartnersRoute
  '/pending-works': typeof AppPendingWorksRoute
  '/reports': typeof AppReportsRoute
  '/salary': typeof AppSalaryRoute
  '/salary-sheet': typeof AppSalarySheetRoute
  '/signature-cards': typeof AppSignatureCardsRoute
  '/sms-sending': typeof AppSmsSendingRoute
  '/staff': typeof AppStaffRouteWithChildren
  '/system-monitor': typeof AppSystemMonitorRoute
  '/targets': typeof AppTargetsRoute
  '/upcoming-payments': typeof AppUpcomingPaymentsRoute
  '/staff/$id': typeof AppStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-bank-investment': typeof AppAgentBankInvestmentRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit-report': typeof AppAuditReportRoute
  '/cash-book': typeof AppCashBookRoute
  '/daily-deposit': typeof AppDailyDepositRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/employee-attendance': typeof AppEmployeeAttendanceRoute
  '/expense': typeof AppExpenseRoute
  '/inventory': typeof AppInventoryRoute
  '/loan-ledger': typeof AppLoanLedgerRoute
  '/monthly-report': typeof AppMonthlyReportRoute
  '/partners': typeof AppPartnersRoute
  '/pending-works': typeof AppPendingWorksRoute
  '/reports': typeof AppReportsRoute
  '/salary': typeof AppSalaryRoute
  '/salary-sheet': typeof AppSalarySheetRoute
  '/signature-cards': typeof AppSignatureCardsRoute
  '/sms-sending': typeof AppSmsSendingRoute
  '/staff': typeof AppStaffRouteWithChildren
  '/system-monitor': typeof AppSystemMonitorRoute
  '/targets': typeof AppTargetsRoute
  '/upcoming-payments': typeof AppUpcomingPaymentsRoute
  '/staff/$id': typeof AppStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agent-bank-investment': typeof AppAgentBankInvestmentRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit-report': typeof AppAuditReportRoute
  '/_app/cash-book': typeof AppCashBookRoute
  '/_app/daily-deposit': typeof AppDailyDepositRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/employee-attendance': typeof AppEmployeeAttendanceRoute
  '/_app/expense': typeof AppExpenseRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/loan-ledger': typeof AppLoanLedgerRoute
  '/_app/monthly-report': typeof AppMonthlyReportRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/pending-works': typeof AppPendingWorksRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/salary': typeof AppSalaryRoute
  '/_app/salary-sheet': typeof AppSalarySheetRoute
  '/_app/signature-cards': typeof AppSignatureCardsRoute
  '/_app/sms-sending': typeof AppSmsSendingRoute
  '/_app/staff': typeof AppStaffRouteWithChildren
  '/_app/system-monitor': typeof AppSystemMonitorRoute
  '/_app/targets': typeof AppTargetsRoute
  '/_app/upcoming-payments': typeof AppUpcomingPaymentsRoute
  '/_app/staff/$id': typeof AppStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent-bank-investment'
    | '/attendance'
    | '/audit-report'
    | '/cash-book'
    | '/daily-deposit'
    | '/dashboard'
    | '/documents'
    | '/employee-attendance'
    | '/expense'
    | '/inventory'
    | '/loan-ledger'
    | '/monthly-report'
    | '/partners'
    | '/pending-works'
    | '/reports'
    | '/salary'
    | '/salary-sheet'
    | '/signature-cards'
    | '/sms-sending'
    | '/staff'
    | '/system-monitor'
    | '/targets'
    | '/upcoming-payments'
    | '/staff/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agent-bank-investment'
    | '/attendance'
    | '/audit-report'
    | '/cash-book'
    | '/daily-deposit'
    | '/dashboard'
    | '/documents'
    | '/employee-attendance'
    | '/expense'
    | '/inventory'
    | '/loan-ledger'
    | '/monthly-report'
    | '/partners'
    | '/pending-works'
    | '/reports'
    | '/salary'
    | '/salary-sheet'
    | '/signature-cards'
    | '/sms-sending'
    | '/staff'
    | '/system-monitor'
    | '/targets'
    | '/upcoming-payments'
    | '/staff/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/agent-bank-investment'
    | '/_app/attendance'
    | '/_app/audit-report'
    | '/_app/cash-book'
    | '/_app/daily-deposit'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/employee-attendance'
    | '/_app/expense'
    | '/_app/inventory'
    | '/_app/loan-ledger'
    | '/_app/monthly-report'
    | '/_app/partners'
    | '/_app/pending-works'
    | '/_app/reports'
    | '/_app/salary'
    | '/_app/salary-sheet'
    | '/_app/signature-cards'
    | '/_app/sms-sending'
    | '/_app/staff'
    | '/_app/system-monitor'
    | '/_app/targets'
    | '/_app/upcoming-payments'
    | '/_app/staff/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upcoming-payments': {
      id: '/_app/upcoming-payments'
      path: '/upcoming-payments'
      fullPath: '/upcoming-payments'
      preLoaderRoute: typeof AppUpcomingPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/targets': {
      id: '/_app/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AppTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-monitor': {
      id: '/_app/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof AppSystemMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sms-sending': {
      id: '/_app/sms-sending'
      path: '/sms-sending'
      fullPath: '/sms-sending'
      preLoaderRoute: typeof AppSmsSendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signature-cards': {
      id: '/_app/signature-cards'
      path: '/signature-cards'
      fullPath: '/signature-cards'
      preLoaderRoute: typeof AppSignatureCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary-sheet': {
      id: '/_app/salary-sheet'
      path: '/salary-sheet'
      fullPath: '/salary-sheet'
      preLoaderRoute: typeof AppSalarySheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary': {
      id: '/_app/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending-works': {
      id: '/_app/pending-works'
      path: '/pending-works'
      fullPath: '/pending-works'
      preLoaderRoute: typeof AppPendingWorksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monthly-report': {
      id: '/_app/monthly-report'
      path: '/monthly-report'
      fullPath: '/monthly-report'
      preLoaderRoute: typeof AppMonthlyReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loan-ledger': {
      id: '/_app/loan-ledger'
      path: '/loan-ledger'
      fullPath: '/loan-ledger'
      preLoaderRoute: typeof AppLoanLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expense': {
      id: '/_app/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof AppExpenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee-attendance': {
      id: '/_app/employee-attendance'
      path: '/employee-attendance'
      fullPath: '/employee-attendance'
      preLoaderRoute: typeof AppEmployeeAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-deposit': {
      id: '/_app/daily-deposit'
      path: '/daily-deposit'
      fullPath: '/daily-deposit'
      preLoaderRoute: typeof AppDailyDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-book': {
      id: '/_app/cash-book'
      path: '/cash-book'
      fullPath: '/cash-book'
      preLoaderRoute: typeof AppCashBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-report': {
      id: '/_app/audit-report'
      path: '/audit-report'
      fullPath: '/audit-report'
      preLoaderRoute: typeof AppAuditReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-bank-investment': {
      id: '/_app/agent-bank-investment'
      path: '/agent-bank-investment'
      fullPath: '/agent-bank-investment'
      preLoaderRoute: typeof AppAgentBankInvestmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$id': {
      id: '/_app/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AppStaffIdRouteImport
      parentRoute: typeof AppStaffRoute
    }
  }
}

interface AppStaffRouteChildren {
  AppStaffIdRoute: typeof AppStaffIdRoute
}

const AppStaffRouteChildren: AppStaffRouteChildren = {
  AppStaffIdRoute: AppStaffIdRoute,
}

const AppStaffRouteWithChildren = AppStaffRoute._addFileChildren(
  AppStaffRouteChildren,
)

interface AppRouteChildren {
  AppAgentBankInvestmentRoute: typeof AppAgentBankInvestmentRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditReportRoute: typeof AppAuditReportRoute
  AppCashBookRoute: typeof AppCashBookRoute
  AppDailyDepositRoute: typeof AppDailyDepositRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmployeeAttendanceRoute: typeof AppEmployeeAttendanceRoute
  AppExpenseRoute: typeof AppExpenseRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLoanLedgerRoute: typeof AppLoanLedgerRoute
  AppMonthlyReportRoute: typeof AppMonthlyReportRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppPendingWorksRoute: typeof AppPendingWorksRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppSalarySheetRoute: typeof AppSalarySheetRoute
  AppSignatureCardsRoute: typeof AppSignatureCardsRoute
  AppSmsSendingRoute: typeof AppSmsSendingRoute
  AppStaffRoute: typeof AppStaffRouteWithChildren
  AppSystemMonitorRoute: typeof AppSystemMonitorRoute
  AppTargetsRoute: typeof AppTargetsRoute
  AppUpcomingPaymentsRoute: typeof AppUpcomingPaymentsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentBankInvestmentRoute: AppAgentBankInvestmentRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditReportRoute: AppAuditReportRoute,
  AppCashBookRoute: AppCashBookRoute,
  AppDailyDepositRoute: AppDailyDepositRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmployeeAttendanceRoute: AppEmployeeAttendanceRoute,
  AppExpenseRoute: AppExpenseRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLoanLedgerRoute: AppLoanLedgerRoute,
  AppMonthlyReportRoute: AppMonthlyReportRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppPendingWorksRoute: AppPendingWorksRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppSalarySheetRoute: AppSalarySheetRoute,
  AppSignatureCardsRoute: AppSignatureCardsRoute,
  AppSmsSendingRoute: AppSmsSendingRoute,
  AppStaffRoute: AppStaffRouteWithChildren,
  AppSystemMonitorRoute: AppSystemMonitorRoute,
  AppTargetsRoute: AppTargetsRoute,
  AppUpcomingPaymentsRoute: AppUpcomingPaymentsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
